# PostgreSQL configuration
#
# Be sure you have the 'pg' gem in your Gemfile:
#   gem "pg"
#
# And set DB_USERNAME / DB_PASSWORD / DB_HOST in your env (or let them default).

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

development:
  <<: *default
  database: fetal_risk_development

test:
  <<: *default
  database: fetal_risk_test

production:
  primary:
    <<: *default
    database: fetal_risk_production
  cache:
    <<: *default
    database: fetal_risk_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: fetal_risk_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: fetal_risk_production_cable
    migrations_paths: db/cable_migrate
