default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: fetal_risk_development

test:
  <<: *default
  database: fetal_risk_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
